name: 'BharatPe Master Action'
description: 'A master repository for BharatPe includes multiple github actions like assets checker, pr bundle analyzer etc.'
author: 'BharatPe'
inputs:
  # Common Requirements
  token:
    description: 'The token to use to access the GitHub API'
    required: true

  # Assets Checker Inputs
  target_folder:
    description: 'The path of directory which contains all your assets ex. src/assets'
    required: true
    default: src/assets
  thrashold_size:
    description: 'Maximum size of assets allowed in Kb ex. 100'
    required: true
    default: 100

  # PR Bundle Analyzer Inputs
  install_command:
    description: 'cli command for installing dependencies ex npm install'
    required: true
    default: 'npm install'
  build_command:
    description: 'cli command for building repository ex npm run build'
    required: true
    default: 'npm run build'
  build_path:
    description: 'output path for the build package'
    required: true
    default: 'build/static'
  base_branch:
    description: 'Branch on which your feature branch will get merge ex. main'
    required: true
    default: 'main'
  head_branch:
    description: 'Branch in which your new changes exists ex. dev'
    required: true
    default: 'main'

runs:
  using: "composite"
  steps:  
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: '16.16.0'

      - uses: bharatpe/pr-bundle-analyzer@main
        with:
          install_command: ${{ inputs.install_command}}
          build_command: ${{ inputs.build_command}}
          build_path: ${{ inputs.build_path}}
          base_branch: ${{ inputs.base_branch}}
          head_branch: ${{ inputs.head_branch}}
          token: ${{ inputs.token }}

      - uses: bharatpe/assets-checker@main
        with:
          token: ${{ inputs.token }}
          target_folder: ${{ inputs.target_folder }}
          thrashold_size: ${{ inputs.thrashold_size }}
           
